### ISSUE TITLE
Promise API

### ISSUE THREAD

**Issue by RomkeVdMeulen** [AvianFlu/ncp#104]
I have a very involved buildscript, with nested buildsteps and callbacks several layers deep. I'd like to rewrite that as a chain of `.then()`.

Are there any plans to support a Promise API with `ncp`?

**Comment by edef1c** [comment]
done: `var ncp = Promise.denodeify(require('ncp').ncp)` (if your promise implementation doesn't have `.denodeify` or an equivalent, maybe check out https://www.npmjs.com/package/promise)

**Comment by mmalecki** [comment]
@nathan7 got it right. We're not going to implement a Promise API in `ncp`, so closing this issue.
