### ISSUE TITLE
option to include hidden files

### ISSUE THREAD

**Issue by andrewrk** [AvianFlu/ncp#27]
Currently ncp does not copy hidden files. I would like the option to copy hidden files.

**Comment by superkhau** [comment]
+1

**Comment by superkhau** [comment]
It does copy hidden files, this should be closed.

**Comment by mmalecki** [comment]
Yup, there is nothing in the code that would prevent `ncp` from copying dotfiles, and I confirmed that it does indeed copy them. Feel free to ping me when you have a test that reproduces this, will reopen then!
