### ISSUE TITLE
Change `const` to `var` for better browserify compatibility.

### ISSUE THREAD

**Issue by MiguelCastillo** [AvianFlu/ncp#56]
I am using bunyan in a project I am "browserifying".  It all works well, but things really collapse when I use more traditional browsers... E.g. IE9.  Any objections to changing `const` to `var`?  The `const modern` variable is never really exposed outside the library so risks are basically limited to your code.

This would really help!  I will submit a PR if you would like me to.

**Comment by mmalecki** [comment]
This line of code was removed in b920f5366b51ba766cc9c7e74a18704fd246b300.
