### ISSUE TITLE
ncp now broken on node v0.12.0 as well as io.js

### ISSUE THREAD

**Issue by TheAlphaNerd** [AvianFlu/ncp#84]
The version of node that landed on Friday is now broken due to the same version check referenced in #79 

I think it is worth escalating now as ncp is broken on stable node.js

/cc @AvianFlu

**Comment by TheAlphaNerd** [comment]
@mmalecki are you a better person to talk to about this?

**Comment by jimthedev** [comment]
@TheAlphaNerd You may have luck switching to ember-cli-ncp. Worked for jspm. Did not check the new node release but certainly worked for iojs.

**Comment by mmalecki** [comment]
We fixed this by removing node v0.8 support in b920f5366b51ba766cc9c7e74a18704fd246b300. Sorry for the delay folks.

**Comment by TheAlphaNerd** [comment]
!!!

**Comment by mmalecki** [comment]
Oh, and this was released as `v2.0.0`.
